import { Component,OnInit } from '@angular/core';

declare var google: any;

@Component({
    moduleId: module.id,
    selector: 'saved-notices-cmp',
    templateUrl: 'saved-notices.component.html'
})

export class MapsComponent {
    // data = [{
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //     "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //     "Product" : "Greg Twohig",
    //     "PrimaryContact" : "Greg Twohig",
    //     "SupportabilityEngineer" : "Corinne Frances White",
    //     "InternalResource" : "COMM-1374 Google Doc",
    //     "CustomerResource" : "TwiML Wagtail",
    //     "slack" : "#tmp-normalizing-twiml-message-attributes",
    //     "AdvisorDetails" : "tmp",
    //     "ZendeskTag" : "comm_1374",
    //     "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //     "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     },
    //     {
    //         "Subject" : "Normalizing the Twilio TwiML <Message> Action Attribute, Effective July 5, 2023",
    //         "Product" : "Greg Twohig",
    //         "PrimaryContact" : "Greg Twohig",
    //         "SupportabilityEngineer" : "Corinne Frances White",
    //         "InternalResource" : "COMM-1374 Google Doc",
    //         "CustomerResource" : "TwiML Wagtail",
    //         "slack" : "#tmp-normalizing-twiml-message-attributes",
    //         "AdvisorDetails" : "tmp",
    //         "ZendeskTag" : "comm_1374",
    //         "Details" : "You’re receiving this notice from Twilio because you’ve used “Alice” voices for Text-To-Speech in the past 90 days.",
    //         "WhatdoyouneedtoDo?" : "Effective June 26 2023, “Alice” voices won’t be supported for Text-To-Speech; requests for Alice voices will be redirected to an alternative voice. We don’t expect service disruption due to this change, but we highly recommend that you update your configurations in the Twilio Console, Studio flows, and application to remove Alice references. After June 26, 2023, Alice voices will be mapped to the existing “Woman” voices when language is available, and requests for non-available languages will be mapped to a paid alternative, as described in our Changes to Alice Text-to-Speech voice (2023) help center article. Free voice alternatives and Alice voices are comparable in quality; the paid alternative voices remain the highest quality voices Twilio offers.",
    //     }
    // ];

    data = [
        {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      },
      {
        "ID": "1",
        "createdDate": "2017-11-06",
        "lastUpdateDate": "2018-03-06",
        "inactiveDate": "2017-12-06",
        "activeInd": "1",
        "productName": "RestAPI",
        "subject": "Subresources now accessible directly by channel UniqueName",
        "SupportabilityEngineer": "Noel Gaffeny",
        "InternalResource": "COMM-1374 Google Doc",
        "CustomerResource": "Rest API Wagtail",
        "slack": "#tmp-support-twilio-live",
        "AdvisorDetails": "tmp",
        "ZendeskTag": "comm_1374",
        "tags": "#RESTAPI#Channel#UniqueName",
        "details": "Channel subresources now accessible directly by channel UniqueName for all operations (GET, POST, DELETE)",
        "priority": "Medium",
        "whatDoYouNeedToDo": "Do anything.",
        "comments": "Comments by other users/viewers if any",
        "person": {
          "personID": 1002,
          "name": "Junaid Mollah",
          "email": "jmollah@twilio.com"
        }
      }
    ]

}
